### ISSUE TITLE
Example code in documentation not running

### ISSUE THREAD

**Issue by ndortega** [abonander/img_hash#21]
I'm trying to run the example code and was unable to circumvent this error: "the trait `img_hash::HashImage` is not implemented for `image::DynamicImage`". Could you look into this??

![screen shot 2017-08-22 at 11 40 44 am](https://user-images.githubusercontent.com/22534471/29574287-1d0a90a8-872f-11e7-9559-c8d2ed3effff.png)

**Comment by abonander** [comment]
Type errors like this usually mean a version mismatch; the version of the `image` crate that you're using isn't the same version that `img_hash` is using. Try using `image = "0.13"` in your `Cargo.toml` and see if it builds then.

**Comment by rasky** [comment]
Found this. Currently, `img_hash` requires `image <= 0.13` in its `Cargo.toml`. Any reason for forcing this? It means it doesn't work with latest `image` version which is 0.19.

**Comment by rasky** [comment]
FWIW, `image = *` is the suggested way to add the image crate (see their README). I suggest that you find a more future proof way to declare the dependency or you’ll have to track upstream even if they don’t break the API.

**Comment by abonander** [comment]
That's really not my problem. It's the user's responsibility to pin the version they've built against or accept breakages on arbitrary upgrades. Cargo should really be warning about wildcard dependency versions. My goal with `img_hash` is to provide as wide of a dependency range compatibility as possible.

**Comment by abonander** [comment]
Published `2.1.0`
