### ISSUE TITLE
Comparison with https://www.phash.org/

### ISSUE THREAD

**Issue by route** [abonander/img_hash#22]
First of all thanks for this library because C implementation is fully abandoned. I've been doing some tests (in our database we rely on phash dct u32 hashes) and it looks like theres a difference from what phash produces and img_hash. Hashes are completely different like 10424892573973741600 vs 14502596198080605850. I used to use ph_dct_imagehash function which produced the latter one. I just wonder is that because of different algo?

**Comment by abonander** [comment]
The implementation is probably not comparable. I haven't actually looked at the pHash source because its license isn't compatible anyway. This crate uses floating-point DCT so if pHash is doing an integer DCT that might explain it (though I have no idea how you'd go about implementing that).

**Comment by route** [comment]
@abonander thanks for explanation.
